#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     SensorIR,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     SensorColor,    sensorI2CHiTechnicColor)
#pragma config(Sensor, S4,     SensorSonic,    sensorI2CMuxController)
#pragma config(Motor,  motorB,           ,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorDb,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorEb,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	char msg[2] = {'n', 'n'};
	char msg2[2] = {'n', 'n'};
	int charStart = 0;
	int power = 0;
	float p = 0;

	while(true)
	{
		if(msg[1] != 'n')
		{
			//PlayTone(500, 100);

			char m1 = msg[0];
			char m2 = msg[1];

			msg2 = msg;

			string p1 = "0";

			if (m2 != 'z')
				p1 = m2;

			power = atoi(p1) * 10;

			string mstr = m1 + m2;
			nxtDisplayCenteredTextLine(2, mstr);

			if (m1 == 'l')
			{
				motor[motorF] = power * -1;
				motor[motorG] = power * -1;
			}
			else if (m1 == 'L')
			{
				motor[motorF] = power;
				motor[motorG] = power;
			}
			else if (m1 == 'r')
			{
				motor[motorH] = power * -1;
				motor[motorI] = power * -1;
			}
			else if (m1 == 'R')
			{
				motor[motorH] = power;
				motor[motorI] = power;
			}
			else if (m1 == 'b')
			{
				motor[motorE] = power * -1;
			}
			else if (m1 == 'B')
			{
				motor[motorE] = power;
			}
			else if (m1 == 'f')
			{
				motor[motorD] = power * -1;
			}
			else if (m1 == 'F')
			{
				motor[motorD] = power;
			}
			else if (m1 == 's' || m1 == 'S')
			{
				servo[servo2] = power;
			}
			p = power;

			msg[0] = 'n';
			msg[1] = 'n';
			msg[2] = 'n';
			power = 0;

			charStart = motor[motorH];
		}

		if(message != 0)
		{
			msg[0] = messageParm[0];
			msg[1] = messageParm[1];

			ClearMessage();
		}
	}

}
